import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, existsSync, renameSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';

const isoNow=()=>new Date().toISOString();
const safeJson=value=>JSON.stringify(value??null);
const localDay=value=>{const d=new Date(value);if(Number.isNaN(d.valueOf()))return '';const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;};
const summaryFor=job=>job.kind==='write'?`Write ${job.path||'file'}`:job.kind==='test'?`Run project tests`:job.kind==='process'?`Managed ${job.shell||''} process`.trim():job.kind==='command'?`Run ${job.shell||''} command`.trim():String(job.kind||'Work');
const compactMeta=job=>({shell:job.shell??null,cwd:job.cwd??null,task:job.task??null,pid:job.pid??null,process_started_at:job.process_started_at??null,process_finished_at:job.process_finished_at??null,output_truncated:Boolean(job.output_truncated),restored:Boolean(job.restored),result:job.result?{exit_code:job.result.exit_code??null,stopped:job.result.stopped??null,sha256:job.result.sha256??null,path:job.result.path??null,backup_available:job.result.backup_available??null}:null,error:job.error??null});

function preflightVault(dbPath){
  if(!existsSync(dbPath))return null;let db=null;
  try{db=new DatabaseSync(dbPath,{readOnly:true});const rows=db.prepare('PRAGMA quick_check').all();const value=rows[0]?.quick_check??Object.values(rows[0]||{})[0]??'';const ok=rows.length===1&&String(value).toLowerCase()==='ok';if(!ok){const error=new Error('Vault quick_check reported corruption.');error.code='PCBRIDGE_VAULT_CORRUPT';throw error;}return null;}
  catch(error){if(error.code==='PCBRIDGE_VAULT_CORRUPT'||/file is not a database|database disk image is malformed|database.*malformed|SQLITE_CORRUPT/i.test(String(error.message)))return error;throw error;}
  finally{try{db?.close();}catch{}}
}
function quarantineVault(root,dbPath,error){const qdir=path.join(root,'quarantine');mkdirSync(qdir,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-'),tag=randomUUID().slice(0,8),files=[];for(const suffix of ['','-wal','-shm']){const source=dbPath+suffix;if(!existsSync(source))continue;const target=path.join(qdir,`vault-${stamp}-${tag}.sqlite${suffix}`);renameSync(source,target);files.push(target);}return {recovered_at:isoNow(),reason:String(error.message),quarantined:files,snapshots_reindexed:undefined};}

export class Vault {
  static open({dataDir}){const root=path.join(dataDir,'vault'),dbPath=path.join(root,'vault.sqlite');mkdirSync(root,{recursive:true});const corrupt=preflightVault(dbPath);const recovery=corrupt?quarantineVault(root,dbPath,corrupt):null;const vault=new Vault({dataDir});vault.recovery=recovery;return vault;}
  constructor({dataDir}){
    this.root=path.join(dataDir,'vault');mkdirSync(this.root,{recursive:true});this.dbPath=path.join(this.root,'vault.sqlite');this.recovery=null;this.db=new DatabaseSync(this.dbPath);
    this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA foreign_keys=ON;PRAGMA busy_timeout=3000;
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT INTO meta(key,value) VALUES('schema_version','1') ON CONFLICT(key) DO NOTHING;
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,name TEXT NOT NULL,root TEXT NOT NULL,first_seen TEXT NOT NULL,last_seen TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,job_id TEXT UNIQUE,project_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,local_day TEXT NOT NULL,kind TEXT NOT NULL,state TEXT NOT NULL,summary TEXT NOT NULL,path TEXT,cwd TEXT,receipt_hash TEXT,metadata_json TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_events_day ON events(local_day,created_at);CREATE INDEX IF NOT EXISTS idx_events_project ON events(project_id,created_at);
CREATE TABLE IF NOT EXISTS artifacts(id TEXT PRIMARY KEY,event_id TEXT,project_id TEXT,path TEXT NOT NULL,sha256 TEXT,kind TEXT NOT NULL,created_at TEXT NOT NULL,local_day TEXT NOT NULL,FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE SET NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_artifacts_project ON artifacts(project_id,created_at);CREATE INDEX IF NOT EXISTS idx_artifacts_day ON artifacts(local_day,created_at);
CREATE TABLE IF NOT EXISTS snapshots(id TEXT PRIMARY KEY,project_id TEXT,kind TEXT NOT NULL,label TEXT,status TEXT NOT NULL,root TEXT,output_path TEXT,sha256 TEXT,created_at TEXT NOT NULL,local_day TEXT NOT NULL,metadata_json TEXT NOT NULL,FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_snapshots_project ON snapshots(project_id,created_at);CREATE INDEX IF NOT EXISTS idx_snapshots_day ON snapshots(local_day,created_at);
CREATE TABLE IF NOT EXISTS labels(target_type TEXT NOT NULL,target_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(target_type,target_id,key));`);
    this.upsertProject=this.db.prepare(`INSERT INTO projects(id,name,root,first_seen,last_seen) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,root=excluded.root,last_seen=excluded.last_seen`);
    this.upsertEvent=this.db.prepare(`INSERT INTO events(id,job_id,project_id,created_at,updated_at,local_day,kind,state,summary,path,cwd,receipt_hash,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(job_id) DO UPDATE SET project_id=excluded.project_id,updated_at=excluded.updated_at,local_day=excluded.local_day,kind=excluded.kind,state=excluded.state,summary=excluded.summary,path=excluded.path,cwd=excluded.cwd,receipt_hash=excluded.receipt_hash,metadata_json=excluded.metadata_json`);
    this.upsertArtifact=this.db.prepare(`INSERT INTO artifacts(id,event_id,project_id,path,sha256,kind,created_at,local_day) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sha256=excluded.sha256,path=excluded.path,kind=excluded.kind,local_day=excluded.local_day`);
    this.upsertSnapshot=this.db.prepare(`INSERT INTO snapshots(id,project_id,kind,label,status,root,output_path,sha256,created_at,local_day,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,output_path=excluded.output_path,sha256=excluded.sha256,local_day=excluded.local_day,metadata_json=excluded.metadata_json`);
  }
  sync({projects=[],jobs=[],checkpoints=[]}){
    const roots=new Map(projects.map(p=>[p.id,p.root]));const ts=isoNow();this.db.exec('BEGIN IMMEDIATE');
    try{
      for(const p of projects)this.upsertProject.run(p.id,String(p.name||path.basename(p.root)||'Project'),p.root,p.created_at||ts,ts);
      for(const j of jobs){const created=j.created_at||ts;const updated=j.process_finished_at||j.result?.finished_at||created;const eventId=`job:${j.id}`;this.upsertEvent.run(eventId,j.id,j.project_id??null,created,updated,localDay(created),String(j.kind||'work'),String(j.state||'unknown'),summaryFor(j),j.path??null,j.cwd??null,j.receipt_hash??null,safeJson(compactMeta(j)));
        if(j.kind==='write'&&j.path){const root=roots.get(j.project_id);const full=path.isAbsolute(j.path)?j.path:root?path.join(root,...String(j.path).split('/')):j.path;this.upsertArtifact.run(`job:${j.id}:write`,eventId,j.project_id??null,full,j.result?.sha256??j.after_sha256??null,'file_write',created,localDay(created));}
      }
      for(const c of checkpoints){const created=c.created_at||ts;this.upsertSnapshot.run(c.id,c.project_id??null,'git_checkpoint','Git checkpoint',c.restored?'restored':'ready',c.repo_root??null,null,c.commit??null,created,localDay(created),safeJson({head:c.head??null,commit:c.commit??null,restored:Boolean(c.restored)}));}
      this.db.exec('COMMIT');
    }catch(error){this.db.exec('ROLLBACK');throw error;}
    if(this.recovery&&this.recovery.snapshots_reindexed===undefined)this.recovery.snapshots_reindexed=this.reindexSnapshotManifests(projects);
  }
  reindexSnapshotManifests(projects=[]){const snapshotsRoot=path.join(this.root,'snapshots');if(!existsSync(snapshotsRoot))return {indexed:0,skipped:0};const known=new Set(projects.map(p=>p.id));let indexed=0,skipped=0;for(const entry of readdirSync(snapshotsRoot,{withFileTypes:true})){if(!entry.isDirectory())continue;const manifestPath=path.join(snapshotsRoot,entry.name,'source-manifest.json');if(!existsSync(manifestPath))continue;try{const text=readFileSync(manifestPath,'utf8'),manifest=JSON.parse(text);if(manifest.snapshot_version!==1||manifest.kind!=='source_manifest'||!manifest.created_at||!manifest.project?.root)throw Error('Unsupported manifest');const sha256=createHash('sha256').update(text).digest('hex'),projectId=known.has(manifest.project?.id)?manifest.project.id:null;this.recordSnapshot({id:`manifest:${sha256}`,project_id:projectId,kind:'source_manifest',label:manifest.label||'Recovered workspace snapshot',status:'ready',root:manifest.project.root,output_path:manifestPath,sha256,created_at:manifest.created_at,metadata:{file_count:manifest.file_count??null,total_bytes:manifest.total_bytes??null,git_head:manifest.git?.head??null,git_dirty:Boolean(manifest.git?.status?.length),adapter:'builtin-manifest-recovered',recovered_from_manifest:true,original_project_id:manifest.project?.id??null}});indexed++;}catch{skipped++;}}return {indexed,skipped};}
  recordSnapshot(snapshot){const id=snapshot.id||randomUUID(),created=snapshot.created_at||isoNow();this.upsertSnapshot.run(id,snapshot.project_id??null,snapshot.kind||'snapshot',snapshot.label||'Snapshot',snapshot.status||'ready',snapshot.root??null,snapshot.output_path??null,snapshot.sha256??null,created,localDay(created),safeJson(snapshot.metadata??{}));return {...snapshot,id,created_at:created};}
  annotate(targetType,targetId,key,value){const now=isoNow();this.db.prepare(`INSERT INTO labels(target_type,target_id,key,value,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(target_type,target_id,key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).run(targetType,targetId,key,value,now);return {target_type:targetType,target_id:targetId,key,value,updated_at:now};}
  summary(){const projects=this.db.prepare('SELECT COUNT(*) n FROM projects').get().n;const events=this.db.prepare('SELECT COUNT(*) n FROM events').get().n;const artifacts=this.db.prepare('SELECT COUNT(*) n FROM artifacts').get().n;const snapshots=this.db.prepare('SELECT COUNT(*) n FROM snapshots').get().n;const last=this.db.prepare('SELECT created_at,summary,state FROM events ORDER BY created_at DESC LIMIT 1').get()||null;return {db_path:this.dbPath,projects,events,artifacts,snapshots,last_event:last,recovery:this.recovery};}
  month(year,month){if(!Number.isInteger(year)||!Number.isInteger(month)||month<1||month>12)throw Error('Invalid calendar month.');const prefix=`${year}-${String(month).padStart(2,'0')}`;return {year,month,days:this.db.prepare(`SELECT local_day AS day,COUNT(*) AS events,COUNT(DISTINCT project_id) AS projects,SUM(CASE WHEN state='succeeded' THEN 1 ELSE 0 END) AS succeeded,SUM(CASE WHEN state='failed' THEN 1 ELSE 0 END) AS failed FROM events WHERE local_day LIKE ? GROUP BY local_day ORDER BY local_day`).all(prefix+'%')};}
  day(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day))throw Error('Use YYYY-MM-DD.');const events=this.db.prepare(`SELECT e.*,p.name AS project_name,p.root AS project_root FROM events e LEFT JOIN projects p ON p.id=e.project_id WHERE e.local_day=? ORDER BY e.created_at`).all(day).map(e=>({...e,metadata:JSON.parse(e.metadata_json||'{}')}));const artifacts=this.db.prepare(`SELECT a.*,p.name AS project_name FROM artifacts a LEFT JOIN projects p ON p.id=a.project_id WHERE a.local_day=? ORDER BY a.created_at`).all(day);const snapshots=this.db.prepare(`SELECT s.*,p.name AS project_name FROM snapshots s LEFT JOIN projects p ON p.id=s.project_id WHERE s.local_day=? ORDER BY s.created_at`).all(day).map(s=>({...s,metadata:JSON.parse(s.metadata_json||'{}')}));return {day,events,artifacts,snapshots};}
  search(query,limit=50){query=String(query||'').trim();if(!query)return {query,results:[]};const like=`%${query}%`;const results=this.db.prepare(`SELECT e.id,e.created_at,e.local_day,e.kind,e.state,e.summary,e.path,e.cwd,p.name AS project_name,p.root AS project_root FROM events e LEFT JOIN projects p ON p.id=e.project_id WHERE e.summary LIKE ? OR e.path LIKE ? OR e.cwd LIKE ? OR p.name LIKE ? OR p.root LIKE ? ORDER BY e.created_at DESC LIMIT ?`).all(like,like,like,like,like,Math.min(200,Math.max(1,Number(limit)||50)));return {query,results};}
  close(){try{this.db.close();}catch{}}
}
